// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentPortal.Data;

#nullable disable

namespace StudentPortal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241214083359_First_Seeding")]
    partial class First_Seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentPortal.Entities.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ClassTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 12, 14, 8, 32, 0, 0, DateTimeKind.Utc),
                            ModifiedAt = new DateTime(2024, 12, 14, 8, 32, 0, 0, DateTimeKind.Utc),
                            Name = "One"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 12, 14, 8, 32, 0, 0, DateTimeKind.Utc),
                            ModifiedAt = new DateTime(2024, 12, 14, 8, 32, 0, 0, DateTimeKind.Utc),
                            Name = "Two"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 12, 14, 8, 32, 0, 0, DateTimeKind.Utc),
                            ModifiedAt = new DateTime(2024, 12, 14, 8, 32, 0, 0, DateTimeKind.Utc),
                            Name = "Three"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 12, 14, 8, 32, 0, 0, DateTimeKind.Utc),
                            ModifiedAt = new DateTime(2024, 12, 14, 8, 32, 0, 0, DateTimeKind.Utc),
                            Name = "Four"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 12, 14, 8, 32, 0, 0, DateTimeKind.Utc),
                            ModifiedAt = new DateTime(2024, 12, 14, 8, 32, 0, 0, DateTimeKind.Utc),
                            Name = "Five"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 12, 14, 8, 32, 0, 0, DateTimeKind.Utc),
                            ModifiedAt = new DateTime(2024, 12, 14, 8, 32, 0, 0, DateTimeKind.Utc),
                            Name = "Six"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 12, 14, 8, 32, 0, 0, DateTimeKind.Utc),
                            ModifiedAt = new DateTime(2024, 12, 14, 8, 32, 0, 0, DateTimeKind.Utc),
                            Name = "Seven"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 12, 14, 8, 32, 0, 0, DateTimeKind.Utc),
                            ModifiedAt = new DateTime(2024, 12, 14, 8, 32, 0, 0, DateTimeKind.Utc),
                            Name = "Eight"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 12, 14, 8, 32, 0, 0, DateTimeKind.Utc),
                            ModifiedAt = new DateTime(2024, 12, 14, 8, 32, 0, 0, DateTimeKind.Utc),
                            Name = "Nine"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 12, 14, 8, 32, 0, 0, DateTimeKind.Utc),
                            ModifiedAt = new DateTime(2024, 12, 14, 8, 32, 0, 0, DateTimeKind.Utc),
                            Name = "Ten"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 12, 14, 8, 32, 0, 0, DateTimeKind.Utc),
                            ModifiedAt = new DateTime(2024, 12, 14, 8, 32, 0, 0, DateTimeKind.Utc),
                            Name = "Eleven"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 12, 14, 8, 32, 0, 0, DateTimeKind.Utc),
                            ModifiedAt = new DateTime(2024, 12, 14, 8, 32, 0, 0, DateTimeKind.Utc),
                            Name = "Twelve"
                        });
                });

            modelBuilder.Entity("StudentPortal.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StudentTable");
                });
#pragma warning restore 612, 618
        }
    }
}
